---
name: Smartphoton
version: 0.0.30
slug: smartphoton
description: Smartphoton
url: https://domosimple.eu/
ingress: false
#ingress_port: 1890
ingress_stream: false
webui: http://[HOST]:[PORT:1890]
panel_icon: mdi:sitemap
init: false
homeassistant: 2021.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1890/tcp: 1890
ports_description:
  1890/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  message: "custom things"
  onduleur: null
  message: "custom things 2"
  batterie: null
  EASUN: "custom things 3"
  EASUN: null
  #credential_secret: ""
  theme: default
  #http_node:
  #  username: ""
  #  password: ""
  #http_static:
  #  username: ""
  #  password: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  #system_packages: []
  #npm_packages: []
  #init_commands: []
schema:
  onduleur: device(subsystem=tty)
  batterie: device(subsystem=tty)
  EASUN: device(subsystem=tty)
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  #credential_secret: password
  theme: list(default|aurora|cobalt2|dark|dracula|espresso-libre|midnight-red|monoindustrial|monokai|oceanic-next|oled|solarized-dark|solarized-light|tokyo-night|zenburn)?
  #http_node:
  #  username: str
  #  password: password
  #http_static:
  # username: str
  #  password: password
  ssl: bool
  certfile: str
  keyfile: str
  #system_packages:
  #  - str
  #npm_packages:
  #  - str
  #init_commands:
  #  - str
  leave_front_door_open: bool?
  safe_mode: bool?
  max_old_space_size: int?
